# bare minimum configuration needed for a2rchi
name: bare_minimum_configuration #REQUIRED

global:
  TRAINED_ON: "SubMIT and the people who started A2rchi" #REQUIRED

chains:
  chain:
    MODEL_NAME: OpenAIGPT4
    CONDENSE_MODEL_NAME: OpenAIGPT4
    SUMMARY_MODEL_NAME: OpenAIGPT4
  prompts:
    CONDENSING_PROMPT: configs/prompts/condense.prompt #REQUIRED
    MAIN_PROMPT: configs/prompts/submit.prompt #REQUIRED
    SUMMARY_PROMPT: configs/prompts/summary.prompt #REQUIRED
  input_lists: #REQUIRED
    - configs/submit.list
    - configs/miscellanea.list

locations_of_secrets: #REQUIRED
  - ~/.a2rchi/base
  